In [12]:
import torch
import numpy as np
import matplotlib.pyplot as plt

import torchvision

from EBM_Training.utils_ebm_train import *
from models import load_model

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [22]:
dset = torchvision.datasets.CIFAR10('/home/sunaybhat/data', download=True, train=False)
images = torch.tensor(dset.data)

Files already downloaded and verified


In [26]:
 torch.tensor(dset.data).shape

torch.Size([10000, 32, 32, 3])

In [3]:
model = load_model('HLB')

In [5]:
        norm_biases = [p for k, p in model.named_parameters() if 'norm' in k and p.requires_grad]
        other_params = [p for k, p in model.named_parameters() if 'norm' not in k and p.requires_grad]

In [9]:
param_configs = [dict(params=norm_biases, lr=5, weight_decay=5),
                     dict(params=other_params, lr=5, weight_decay=5)]

In [10]:
param_configs

[{'params': [Parameter containing:
   tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          requires_grad=True),
   Parameter containing:
   tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          requires_grad=True),
   Parameter containing:
   tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [2]:
train_data = get_train_data('stl10','/Users/sunaybhat/Documents/GitHub/data')
test_data = get_test_data('stl10','/Users/sunaybhat/Documents/GitHub/data')

print(f'Number of training images: {len(train_data)}')
print(f'Number of test images: {len(test_data)}')

Files already downloaded and verified
Files already downloaded and verified
Number of training images: 100000
Number of test images: 8000


In [9]:
next(iter(train_data))[0].to(device)

tensor([[[-0.0118,  0.1294,  0.1765,  ..., -0.5608, -0.5451, -0.5294],
         [-0.4275, -0.4824, -0.5373,  ..., -0.4980, -0.5686, -0.5373],
         [-0.5294, -0.5373, -0.5843,  ..., -0.8275, -0.8667, -0.8118],
         ...,
         [ 0.4275,  0.4824,  0.5922,  ...,  0.2941,  0.2941,  0.2549],
         [ 0.5216,  0.5765,  0.3961,  ...,  0.3804,  0.3804,  0.4510],
         [ 0.3961,  0.3490,  0.4118,  ...,  0.3647,  0.2706,  0.2549]],

        [[ 0.0039,  0.0824,  0.2000,  ..., -0.6392, -0.6000, -0.6157],
         [-0.3725, -0.4667, -0.5059,  ..., -0.6078, -0.6000, -0.6000],
         [-0.5529, -0.4902, -0.5373,  ..., -0.8745, -0.8745, -0.8745],
         ...,
         [ 0.3647,  0.3490,  0.4980,  ...,  0.2000,  0.2471,  0.1922],
         [ 0.4275,  0.4980,  0.2941,  ...,  0.2863,  0.2784,  0.3490],
         [ 0.2706,  0.2706,  0.3255,  ...,  0.3020,  0.1686,  0.1608]],

        [[ 0.0118,  0.1137,  0.2078,  ..., -0.6392, -0.6627, -0.6235],
         [-0.3020, -0.4118, -0.4353,  ..., -0